version: '2'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: bonner.uk
    networks:
      network:
        ipv4_address: "10.20.30.49"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      ServerIP: 10.20.30.49
      VIRTUAL_HOST: pihole.bonner.uk
      TZ: 'Europe/London'
      DNS1: '1.1.1.1'
      DNS2: '1.0.0.1'
      WEB_PORT: 80
      WEBPASSWORD: 'password01'
    restart: unless-stopped
    volumes:
      - './pihole/etc-pihole/:/etc/pihole/'
      - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'

  unifi-controller:
    container_name: unifi
    image: jacobalberty/unify:latest
    hostname: unifi
    domainname: bonner.uk
    networks:
      network:
        ipv4_address: "10.20.30.48"
    dns:
      - 10.20.30.49
      - 1.1.1.1
    ports:
      - 3478/udp
      - 10001/udp
      - 6789/tcp
      - 8080/tcp
      - 8880/tcp
      - 8443/tcp
      - 8843/tcp
    environment:
      ServerIP: 10.20.30.48
      TZ: 'Europe/London'
    restart: unless-stopped
    volumes:
      - './unifi/data/:/unifi/data'
      - './unifi/cert/:/unifi/cert'

networks:
  network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "10.20.30.0/24"
          gateway: "10.20.30.40"
