version: '2'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: dns
    domainname: bonner.uk
    networks:
      network:
        ipv4_address: "10.10.10.10"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      ServerIP: 10.10.10.10
      VIRTUAL_HOST: dns.bonner.uk
      TZ: 'Europe/London'
      DNS1: '1.1.1.1'
      DNS2: '1.0.0.1'
      WEB_PORT: 80
      WEBPASSWORD: 'password01'
    restart: unless-stopped
    volumes:
      - './pihole/etc-pihole/:/etc/pihole/'
      - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'

  unifi-controller:
    container_name: unifi
    image: jacobalberty/unifi:latest
    hostname: unifi
    domainname: bonner.uk
    networks:
      network:
        ipv4_address: "10.10.10.2"
    dns:
      - 10.10.10.10
      - 1.1.1.1
    ports:
      - 3478/udp
      - 10001/udp
      - 6789/tcp
      - 8080/tcp
      - 8880/tcp
      - 8443/tcp
      - 8843/tcp
    environment:
      ServerIP: 10.10.10.2
      TZ: 'Europe/London'
    restart: unless-stopped
    volumes:
      - './unifi/data/:/unifi/data'
      - './unifi/cert/:/unifi/cert'

  speedtest:
    container_name: speedtest
    image: openspeedtest/latest:latest
    hostname: speedtest
    domainname: bonner.uk
    networks:
      network:
        ipv4_address: "10.10.10.111"
    dns:
      - 10.10.10.10
      - 1.1.1.1
    ports:
            - 80:80
    environment:
      ServerIP: 10.10.10.111
      TZ: 'Europe/London'
    restart: unless-stopped

networks:
  network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "10.10.10.0/24"
          gateway: "10.10.10.1"
