version: '2'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: bonner.uk
    networks:
      network:
        ipv4_address: "10.20.30.49"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      ServerIP: 10.20.30.49
      VIRTUAL_HOST: pihole.bonner.uk
      TZ: 'Europe/London'
      DNS1: '1.1.1.1'
      DNS2: '1.0.0.1'
      WEB_PORT: 80
      WEBPASSWORD: 'password01'
    restart: unless-stopped
    volumes:
        - './pihole/etc-pihole/:/etc/pihole/'
        - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'

networks:
  network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "10.20.30.0/24"
          gateway: "10.20.30.40"
